# Generated by Django 5.1.4 on 2026-09-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_backfill_orcamento_modulo"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("saas", "0004_empresa_modulos_contratados"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_superuser", True),
                    ("perfil", "superadmin"),
                    ("empresa__isnull", False),
                    _connector="OR",
                ),
                name="usuario_nao_superadmin_deve_ter_empresa",
                violation_error_message="Usuário sem perfil de superadmin precisa estar vinculado a uma empresa.",
            ),
        ),
    ]
