[build]
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate --noinput && gunicorn bk_erp.wsgi:application --bind 0.0.0.0:$PORT"

[[crons]]
schedule = "0 7 * * *"
command  = "python manage.py enviar_alertas"
