# Generated by Django 5.1.4 on 2026-09-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0006_remove_legacy_binaryfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="documento_original",
            field=models.ForeignKey(
                blank=True,
                help_text="Preenchido automaticamente quando este registro é uma nova versão de outro documento.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versoes",
                to="documentos.documento",
                verbose_name="Documento Original",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="versao",
            field=models.PositiveIntegerField(default=1, verbose_name="Versão"),
        ),
        migrations.AddField(
            model_name="documento",
            name="vigente",
            field=models.BooleanField(
                default=True,
                help_text="Indica se esta é a versão válida atual do documento.",
                verbose_name="Vigente",
            ),
        ),
    ]
