# Generated by Django 5.1.4 on 2026-03-03 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controledocconfig",
            options={"verbose_name": "Configuração Controle de Documentos"},
        ),
        migrations.AlterModelOptions(
            name="documentocontrole",
            options={
                "ordering": ["id"],
                "verbose_name": "Documento de Controle",
                "verbose_name_plural": "Documentos de Controle",
            },
        ),
        migrations.AlterModelOptions(
            name="projetoacesso",
            options={
                "verbose_name": "Acesso ao Projeto",
                "verbose_name_plural": "Acessos aos Projetos",
            },
        ),
        migrations.AlterField(
            model_name="controledocconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="documentocontrole",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="documentocontrole",
            name="status",
            field=models.CharField(
                choices=[
                    ("nao_iniciado", "Não iniciado"),
                    ("em_andamento", "Em andamento - BK"),
                    ("em_analise", "Em análise - Cliente"),
                    ("em_revisao", "Em revisão - BK"),
                    ("concluido", "Concluído"),
                    ("cancelado", "Cancelado"),
                ],
                default="nao_iniciado",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho"),
                    ("planejamento", "Planejamento"),
                    ("execucao", "Execução"),
                    ("monitoramento", "Monitoramento"),
                    ("encerrado", "Encerrado"),
                    ("suspenso", "Suspenso"),
                ],
                default="rascunho",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="projetoacesso",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="projetoacesso",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos_acesso",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="statuseventodocumento",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projetoacesso",
            unique_together={("projeto", "usuario")},
        ),
    ]
