# Generated by Django 5.1.4 on 2026-04-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_controledocconfig_revisao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
