# Generated by Django 5.1.4 on 2026-04-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_obra_projeto_material_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcadastro',
            name='codigo_bk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Código BK'),
        ),
        migrations.AlterField(
            model_name='materialcadastro',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=255, verbose_name='Código Cliente'),
        ),
        migrations.AlterField(
            model_name='materialcadastro',
            name='descricao',
            field=models.CharField(max_length=1000, verbose_name='Descrição'),
        ),
    ]
